const ROLES = {
  COLLECTOR: 'COLLECTOR',
  RECYCLER: 'RECYCLER',
  ADMIN: 'ADMIN'
};

const LANGUAGES = {
  HI: 'HI',
  MR: 'MR',
  EN: 'EN'
};

const MATERIAL_CATEGORIES = {
  CRT: 'CRT',
  LCD: 'LCD',
  PCB: 'PCB',
  CABLE: 'CABLE',
  BATTERY: 'BATTERY',
  MOTOR: 'MOTOR',
  MAGNET: 'MAGNET',
  MIXED_PLASTIC: 'MIXED_PLASTIC',
  OTHER: 'OTHER'
};

const MATERIAL_CONDITIONS = {
  GOOD: 'GOOD',
  USED: 'USED',
  DAMAGED: 'DAMAGED',
  MIXED: 'MIXED'
};

const SOURCE_TYPES = {
  HOUSEHOLD: 'HOUSEHOLD',
  SHOP: 'SHOP',
  OFFICE: 'OFFICE',
  SCRAP_COLLECTION: 'SCRAP_COLLECTION',
  OTHER: 'OTHER'
};

const LOT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  QUOTE_PENDING: 'QUOTE_PENDING',
  QUOTE_RECEIVED: 'QUOTE_RECEIVED',
  ACCEPTED: 'ACCEPTED',
  HANDOVER_PENDING: 'HANDOVER_PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const WEIGHT_UNITS = {
  KG: 'KG',
  PIECE: 'PIECE',
  TON: 'TON'
};

const AUTHORIZATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED'
};

const TRANSACTION_STATUS = {
  QUOTE_REQUESTED: 'QUOTE_REQUESTED',
  QUOTED: 'QUOTED',
  ACCEPTED: 'ACCEPTED',
  HANDOVER_PENDING: 'HANDOVER_PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_METHODS = {
  CASH: 'CASH',
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIAL: 'PARTIAL'
};

const SAFETY_CATEGORIES = {
  BATTERY: 'BATTERY',
  CRT: 'CRT',
  BURNING: 'BURNING',
  CHEMICAL: 'CHEMICAL',
  GENERAL: 'GENERAL'
};

const TRACEABILITY_STATUS = {
  RECORDED: 'RECORDED',
  VERIFIED: 'VERIFIED'
};

module.exports = {
  ROLES,
  LANGUAGES,
  MATERIAL_CATEGORIES,
  MATERIAL_CONDITIONS,
  SOURCE_TYPES,
  LOT_STATUS,
  WEIGHT_UNITS,
  AUTHORIZATION_STATUS,
  TRANSACTION_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  SAFETY_CATEGORIES,
  TRACEABILITY_STATUS
};
